CREATE OR REPLACE PROCEDURE EXECUTOR.CREATEINTEGRATIONACTIVITY(
	IN INTEGRATIONACTIVITYID UUID,
	IN INTEGRATIONREQUESTMESSAGE XML,
	OUT INTEGRATIONID UUID)
LANGUAGE 'PLPGSQL'
AS $BODY$
DECLARE
	VALIDINTEGRATIONACTIVITYID UUID;
BEGIN
	BEGIN
        SELECT EXECUTOR.EXECUTORACTIVITY.ACTIVITYID FROM EXECUTOR.EXECUTORACTIVITY WHERE EXECUTOR.EXECUTORACTIVITY.ACTIVITYID=INTEGRATIONACTIVITYID INTO STRICT VALIDINTEGRATIONACTIVITYID;
        EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    RAISE EXCEPTION 'ACTIVITYID % NOT FOUND', INTEGRATIONACTIVITYID;
                WHEN TOO_MANY_ROWS THEN
                    RAISE EXCEPTION 'ACTIVITYID % NOT UNIQUE', INTEGRATIONACTIVITYID;
    END;
	
	INSERT INTO EXECUTOR.EXECUTORINTEGRATIONACTIVITY(ACTIVITYID,REQUESTMESSAGE)
	VALUES(VALIDINTEGRATIONACTIVITYID,INTEGRATIONREQUESTMESSAGE)
	RETURNING EXECUTOR.EXECUTORINTEGRATION.INTEGRATIONID INTO INTEGRATIONID;
END
$BODY$;
ALTER PROCEDURE EXECUTOR.CREATEINTEGRATIONACTIVITY(UUID, XML)
    OWNER TO POSTGRES;
