CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORACTIVITYSTATE
(
    STATEID SMALLINT NOT NULL,
    STATE TEXT NOT NULL,
    CONSTRAINT PK_EXECUTORACTIVITYSTATE_STATEID PRIMARY KEY (STATEID),
    CONSTRAINT UK_EXECUTORACTIVITYSTATE_STATE UNIQUE (STATE)
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORACTIVITYSTATE
    OWNER TO POSTGRES;