CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORJOBTYPE
(
    TYPEID SERIAL NOT NULL,
    TYPE TEXT  NOT NULL,
    SEQUENTIALEXECUTION BOOLEAN NOT NULL DEFAULT FALSE,
    MAXRETRIESALLOWED INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT PK_EXECUTORJOBTYPE_TYPEID PRIMARY KEY (TYPEID),
    CONSTRAINT UK_EXECUTORJOBTYPE_TYPE UNIQUE (TYPE)
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORJOBTYPE
    OWNER TO POSTGRES;