CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORJOBPRIORITY
(
    PRIORITYID SMALLINT NOT NULL,
    PRIORITY TEXT NOT NULL,
    CONSTRAINT PK_EXECUTORJOBPRIORITY_PRIORITYID PRIMARY KEY (PRIORITYID),
    CONSTRAINT UK_EXECUTORJOBPRIORITY_PRIORITY UNIQUE (PRIORITY)
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORJOBPRIORITY
    OWNER TO POSTGRES;