CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORINTEGRATIONACTIVITY
(
    INTEGRATIONID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    ACTIVITYID UUID NOT NULL,
    REQUESTMESSAGE XML,
    RESPONSEMESSAGE XML,
    EXCEPTIONMESSAGE XML,
    CONSTRAINT PK_EXECUTORINTEGRATIONACTIVITY_INTEGRATIONID PRIMARY KEY (INTEGRATIONID),
    CONSTRAINT FK_EEXECUTORINTEGRATIONACTIVITY_ACTIVITYID FOREIGN KEY (ACTIVITYID)
        REFERENCES EXECUTOR.EXECUTORACTIVITY (ACTIVITYID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORINTEGRATIONACTIVITY
    OWNER TO POSTGRES;