CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORINTEGRATIONCONFIGURATION
(
    INTEGRATIONID UUID NOT NULL,
    ENDPOINT TEXT COLLATE PG_CATALOG.DEFAULT NOT NULL,
    CHANNEL TEXT COLLATE PG_CATALOG.DEFAULT NOT NULL,
    TIMEOUT INTEGER NOT NULL,
    CONSTRAINT PK_EXECUTORINTEGRATIONCONFIGURATION_INTEGRATIONID PRIMARY KEY (INTEGRATIONID)
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORINTEGRATIONCONFIGURATION
    OWNER TO POSTGRES;