CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORACTIVITY
(
    ACTIVITYID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    ACTIVITYTYPEID SMALLINT NOT NULL,
    ACTIVITYSTATEID SMALLINT NOT NULL,
    ACTIVITYNAME TEXT NOT NULL,
    ACTIVITYSEQUENCE TEXT NOT NULL,
    TASKID UUID NOT NULL,
    CREATEDBY UUID NOT NULL,
    CREATEDON TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EXECUTORACTIVITY_ACTIVITYID PRIMARY KEY (ACTIVITYID),
    CONSTRAINT UK_EXECUTORACTIVITY_TASKID_ACTIVITYSEQUENCE UNIQUE (TASKID, ACTIVITYSEQUENCE),
    CONSTRAINT FK_EXECUTORACTIVITY_ACTIVITYSTATEID FOREIGN KEY (ACTIVITYSTATEID)
        REFERENCES EXECUTOR.EXECUTORACTIVITYSTATE (STATEID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_EXECUTORACTIVITY_ACTIVITYTYPEID FOREIGN KEY (ACTIVITYTYPEID)
        REFERENCES EXECUTOR.EXECUTORACTIVITYTYPE (TYPEID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_EXECUTORACTIVITY_TASKID FOREIGN KEY (TASKID)
        REFERENCES EXECUTOR.EXECUTORTASK (TASKID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORACTIVITY
    OWNER TO POSTGRES;