CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORACTIVITYTYPE
(
    TYPEID SMALLINT NOT NULL,
    TYPE TEXT NOT NULL,
    CONSTRAINT PK_EXECUTORACTIVITYTYPE_TYPEID PRIMARY KEY (TYPEID),
    CONSTRAINT UK_EXECUTORACTIVITYTYPE_TYPE UNIQUE (TYPE)
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORACTIVITYTYPE
    OWNER TO POSTGRES;