CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORJOB
(
    EXECUTORID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    EXECUTORTYPEID SMALLINT NOT NULL,
    EXECUTORPRIORITYID SMALLINT NOT NULL,
    EXECUTORSTATEID SMALLINT NOT NULL,
    CREATEDBY UUID NOT NULL,
    CREATEDON TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXECUTOREFFECTIVEDATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT PK_EXECUTORJOB_EXECUTORID PRIMARY KEY (EXECUTORID),
    CONSTRAINT FK_EXECUTORJOB_EXECUTORPRIORITYID_PRIORITYID FOREIGN KEY (EXECUTORPRIORITYID)
        REFERENCES EXECUTOR.EXECUTORJOBPRIORITY (PRIORITYID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_EXECUTORJOB_EXECUTORSTATEID_STATEID FOREIGN KEY (EXECUTORSTATEID)
        REFERENCES EXECUTOR.EXECUTORJOBSTATE (STATEID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_EXECUTORJOB_EXECUTORTYPEID_TYPEID FOREIGN KEY (EXECUTORTYPEID)
        REFERENCES EXECUTOR.EXECUTORJOBTYPE (TYPEID) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORJOB
    OWNER TO POSTGRES;