CREATE TABLE IF NOT EXISTS EXECUTOR.EXECUTORTASKSTATE
(
    STATEID SMALLINT NOT NULL,
    STATE TEXT NOT NULL,
    CONSTRAINT PK_EXECUTORTASKSTATE_STATEID PRIMARY KEY (STATEID),
    CONSTRAINT UK_EXECUTORTASKSTATE_STATE UNIQUE (STATE)
);

ALTER TABLE IF EXISTS EXECUTOR.EXECUTORTASKSTATE
    OWNER TO POSTGRES;